function str = instrDB(task, english_on)

if english_on
    switch task
        case 'DotRot'
            str = ['\nIn this exprtiment one set of dots in a circular shape will be displayed.' ...
                '\nThe direction may change at any time. Please determine its moving direction. ' ...
                '\n' ...
                '\nPress and hold UP key for INWARD moving direction.' ...
                '\nPress and hold DOWN key for OUTWARD moving direction.' ...
                '\n' ...
                '\nPress as long as you can decide. If you are not certain, you can press no key. ' ...
                '\nBut this time should not last too long!' ...
                '\n' ...
                '\n' ...
                '\nPress any key to continue.'];

        case 'ImEval'
            str = ['\nEvaluate the overall emotion of the face stimuli or blank stimuli' ...
                '\nboth as CORRECT and QUICK as possible.' ...
                '\n' ...
                '\nChoose a number from 1 to 7, and press Number key.' ...
                '\n' ...
                '\n1:angry - 4:neutral - 7:happy' ...
                '\n' ...
                '\n' ...
                '\nPress any key to continue.'];

        case 'Octal'
            str = ['\nIn this exprtiment 3 sets of dots in the shape of a walking man will be displayed. ' ...
                '\nThe direction may change at any time. Please determine th walkers''s  OVERALL walking direction.' ...
                '\n' ...
                '\nPress and hold UP key for INWARD moving direction.' ...
                '\nPress and hold DOWN key for OUTWARD moving direction.' ...
                '\n' ...
                '\nPress as long as you can decide. If you are not certain, you can press no key. ' ...
                '\nBut this time should not last too long!' ...
                '\n' ...
                '\n' ...
                '\nPress any key to continue.'];

        case 'Direction'
            str = ['In this exprtiment one set of dots in the shape of a walking man will be displayed. ' ...
                '\nPlease PRESS and HOLD the pedal corresponding the walker''s walking direction you saw.' ...
                '\n' ...
                '\nPress and hold Right key for moving direction Right.' ...
                '\nPress and hold Left key for OUTWARD direction Left.' ...
                '\n' ...
                '\nPress as long as you can decide. If you are not certain, you can press no key. ' ...
                '\nBut this time should not last too long!' ...
                '\n' ...
                '\n' ...
                '\nPress any key to continue.'];

        case 'Many'
            str = ['In this exprtiment two types of colored dots in the shape of a walking man will be displayed.' ...
                '\nPlease PRESS and HOLD the pedal corresponding the number of the color of the dots.' ...
                '\n' ...
                '\nIf the majority of the dots you saw on the screen is RED, press LEFT pedal.'...
                '\nIf the majority of the dots you saw on the screen is GREEN, press RIGHT pedal.'...
                '\n' ...
                '\n' ...
                '\n' ...
                '\nPress any key to continue.'];
        case 'rest'
            str = ['\nPlease rest for 30 seconds.' ...
                '\n' ...
                '\nIf you want to proceed, press any button.'];
        otherwise
            str = ['Unknown task!'];
    end
else
    switch task
        case 'DotRot'
            str = ['\n\n本实验中，一群圆形点将呈现在屏幕中。请判断这些点整体上的运动方向。' ...
                '\n\n点运动方向随时可能切换。一旦发现切换，请作出相应按键反应。' ...
                '\n\n' ...
                '\n\n如果发现运动方向垂直屏幕向里，请按住键盘 上键 不放。' ...
                '\n\n如果发现运动方向垂直屏幕向外，请按住键盘 下键 不放。' ...
                '\n\n' ...
                '\n\n只要您能判断运动方向，就按住相应键不放作出反应。' ...
                '\n\n如果您无法判断运动方向，可以暂时不做反应。' ...
                '\n\n但每次不做反应的时间不能过长。'];

        case 'ImEval'
            str = ['\n\n屏幕上将会呈现若干面孔情绪图或者空白图。请评价整体情绪。' ...
                '\n\n可以通过键盘上 1 到 7 之间任意数作出反应。' ...
                '\n\n' ...
                '\n\n1 表示愤怒，4 表示中性， 7 表示高兴。' ...
                '\n\n' ...
                '\n\n注意：请越快越准做反应。' ...
                '\n\n' ...
                '\n\n按任意键开始'];

        case 'Octal'
            str = ['\n\n本实验中，一群人形点将呈现在屏幕中。人运动方向随时可能切换。' ...
                '\n\n请判断这些人整体上的运动方向。一旦发现切换，请作出相应按键反应。' ...
                '\n\n' ...
                '\n\n如果发现运动方向垂直屏幕向里，请按住键盘 上键 不放。' ...
                '\n\n如果发现运动方向垂直屏幕向外，请按住键盘 下键 不放。' ...
                '\n\n' ...
                '\n\n只要您能判断运动方向，就按住相应键不放作出反应。' ...
                '\n\n如果您无法判断运动方向，可以暂时不做反应（不按任何键）。' ...
                '\n\n但每次不做反应的时间不能过长。'];

        case 'Direction'
            str = ['\n\n本实验中，一群圆形点将呈现在屏幕中。点运动方向随时可能切换。' ...
                '\n\n请判断这些点整体上的运动方向。一旦发现切换，请作出相应按键反应。' ...
                '\n\n' ...
                '\n\n如果发现运动方向垂直屏幕向里，请按住键盘 上键 不放。' ...
                '\n\n如果发现运动方向垂直屏幕向外，请按住键盘 下键 不放。' ...
                '\n\n' ...
                '\n\n只要您能判断运动方向，就按住相应键不放作出反应。' ...
                '\n\n如果您无法判断运动方向，可以暂时不做反应（不按任何键）。' ...
                '\n\n但每次不做反应的时间不能过长。'];

        case 'Many'
            str = ['\n\n您将看到一个行走的点光人，分别呈红色和绿色。' ...
                '\n\n请用脚踏板作出反应。当看到的多数点为红色时，请用右边脚踏板。' ...
                '\n\n当看到的多数点为绿色时，请用左边脚踏板。' ...
                '\n\n' ...
                '\n\n若理解上述指示，请按任意键继续。'];

        case 'Simple'
            str = ['\n\n本实验中，一个人形点将呈现在屏幕中。人运动方向随时可能切换。' ...
                '\n\n请判断这个人的运动方向。一旦发现切换，请作出相应按键反应。' ...
                '\n\n' ...
                '\n\n如果发现运动方向垂直屏幕向里，请按住键盘 上键 不放。' ...
                '\n\n如果发现运动方向垂直屏幕向外，请按住键盘 下键 不放。' ...
                '\n\n' ...
                '\n\n只要您能判断运动方向，就按住相应键不放作出反应。' ...
                '\n\n如果您无法判断运动方向，可以暂时不做反应（不按任何键）。' ...
                '\n\n但每次不做反应的时间不能过长。'];

        case 'Single'
            str = ['\n\n本实验中，一个人形点将呈现在屏幕中。人运动方向随时可能切换。' ...
                '\n\n请判断这个人的运动方向。一旦发现切换，请作出相应按键反应。' ...
                '\n\n' ...
                '\n\n如果发现运动方向垂直屏幕向里，请按住键盘 上键 不放。' ...
                '\n\n如果发现运动方向垂直屏幕向外，请按住键盘 下键 不放。' ...
                '\n\n' ...
                '\n\n只要您能判断运动方向，就按住相应键不放作出反应。' ...
                '\n\n如果您无法判断运动方向，可以暂时不做反应（不按任何键）。' ...
                '\n\n但每次不做反应的时间不能过长。'];

        case 'rest'
            str = ['\n\n请休息30秒。' ...
                '\n\n' ...
                '\n\n请按任意键继续。'];
        otherwise
            str = ['未知任务'];
    end

end
